# -*- coding: utf-8 -*-
"""Muhammad Reva Putrasardjono.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iarOsXg7VusNG9Vb_AzQX0_9vCuagL3I
"""

P1 ={"Nama":"Budi", "Jabatan":"Manager", "Agama":"Islam", "Status":"Menikah"}
P2 ={"Nama":"Siti", "Jabatan":"Asistant Manager", "Agama":"Islam", "Status":"Menikah"}
P3 ={"Nama":"Gede", "Jabatan":"Supervisor", "Agama":"Hindu", "Status":"Menikah"}
P4 ={"Nama":"Joko", "Jabatan":"Staff", "Agama":"Islam", "Status":"Belum Menikah"}
P5 ={"Nama":"Alex", "Jabatan":"Staff", "Agama":"Kristen Protestan", "Status":"Belum Menikah"}

ar_karyawan = [P1, P2, P3, P4, P5]

for data in ar_karyawan:
  if data["Jabatan"] == "Manager":
    Gaji = "Rp.15.000.000"
    TJ = "Rp.4.500.000"
    BPJS = "Rp.1.500.000"
    TK = "Rp.1.500.000"
    GK = "Rp.22.500.000"
    GB = "Rp.22.562.500"
  if data["Jabatan"] == "Asistant Manager":
    Gaji = "Rp.10.000.000"
    TJ = "Rp.3.000.000"
    BPJS = "Rp.!.000.000"
    TK = "Rp.1.500.000"
    GK = "Rp.15.000.000"
    GB = "Rp.15.375.000"
  if data["Jabatan"] == "Supervisor":
    Gaji = "Rp.7.000.000"
    TJ = "Rp.2.100.000"
    BPJS = "Rp.700.000"
    TK = "Rp.1.500.000"
    GK = "Rp.10.500.000"
    GB = "Rp.10.762.500"
  if data["Jabatan"] == "Staff":
    Gaji = "Rp.4.000.000"
    TJ = "Rp.1.200.000"
    BPJS = "Rp.400.000"
    TK = "0%"
    GK = "Rp.5.600.000"
    GB = "Rp.5.740.000"
  if data["Agama"] == "Islam":
    ZP = "2,5%"
  if data["Agama"] == "Hindu":
    ZP = "0%"
  if data["Agama"] == "Kristen Protestan":
    ZP = "0%"

  print(
      "---------------------------------",
      "\nNama Karyawan \t\t:", data["Nama"],
      "\nJabatan \t\t:", data["Jabatan"],
      "\nAgama \t\t\t:", data["Agama"],
      "\nStatus \t\t\t:", data["Status"],
      "\nGaji \t\t\t:", Gaji,
      "\nTunjangan Jabatan \t:", TJ,
      "\nBPJS \t\t\t:", BPJS,
      "\nTunjangan Keluarga \t:", TK,
      "\nGaji Kotor \t\t:", GK,
      "\nZakat Profesi \t\t:", ZP,
      "\nGaji Bersih \t\t:", GB
  )